---
development:
  cloud_name: djy5jjomj
  api_key: '797847712352483'
  api_secret: 9DQcJGk5mztpyPGADrEVt3TsDDc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: djy5jjomj
  api_key: '797847712352483'
  api_secret: 9DQcJGk5mztpyPGADrEVt3TsDDc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: djy5jjomj
  api_key: '797847712352483'
  api_secret: 9DQcJGk5mztpyPGADrEVt3TsDDc
  enhance_image_tag: true
  static_image_support: false
